language: R
warnings_are_errors: true
dist: trusty
sudo: true
cache: packages

after_success:
    - Rscript -e "source ('https://install-github.me/MangoTheCat/goodpractice')"
      #- Rscript -e "source ('https://install-github.me/MangoTheCat/goodpractice')"
      #- Rscript -e 'library(goodpractice);gp(checks=all_checks()[grepl("(rcmdcheck|covr)",all_checks())])'
      #- Rscript -e 'library(goodpractice);gp(checks=all_checks())'
