language: R
warnings_are_errors: true
sudo: true
cache: packages

addons:
    apt:
        source:
            - travis-ci/sqlite3
        packages:
            - sqlite3
            - libsqlite3-dev
            - libsqlite3-0
