# Download script file from GitHub - DO NOT CHANGE
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
    - ps: Bootstrap
      #- cinst curl sqlite # installs win32-x86 version
    - choco install curl 
      #- refreshenv
      #- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
      #- ps: Start-FileDownload 'http://sqlite.org/2017/sqlite-dll-win64-x64-3180000.zip'
      #- cmd: 7z e sqlite-dll-win64-x64-3180000.zip -y > nul
    - ps: Start-FileDownload 'http://sqlite.org/2017/sqlite-amalgamation-3180000.zip'
      #- cmd: 7z e sqlite-amalgamation-3180000.zip -oC:\tools\sqlite -y > nul
    - cmd: 7z e sqlite-amalgamation-3180000.zip -y > nul
    - refreshenv
    - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER% 
    - SET SQLITE3_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER% 

# Adapt as necessary starting from here

environment:
    matrix:
        - R_VERSION: release
          R_ARCH: x64

build_script:
    - travis-tool.sh install_deps

test_script:
    - travis-tool.sh run_tests

on_failure:
    - 7z a failure.zip *.Rcheck\*
    - appveyor PushArtifact failure.zip

artifacts:
    - path: '*.Rcheck\**\*.log'
      name: Logs

    - path: '*.Rcheck\**\*.out'
      name: Logs

    - path: '*.Rcheck\**\*.fail'
      name: Logs

    - path: '*.Rcheck\**\*.Rout'
      name: Logs

    - path: '\*_*.tar.gz'
      name: Bits

    - path: '\*_*.zip'
      name: Bits
