# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_import_stn_df
#'
#' Import a data.frame of station (id, name, lon, lat) into the SQLite3
#' database. Used for London and Chicago, for both of which stations are loaded
#' within R and passed to this function.
#'
#' @param dbcon Active connection to sqlite3 database
#' @param stn_data An R DataFrame of (id, name, lon, lat) for all stations
#'
#' @return Number of stations to potentially be added to stations table (if not
#'         already there).
#'
#' @noRd
rcpp_import_stn_df <- function(bikedb, stn_data, city) {
    .Call('sqlite3test_rcpp_import_stn_df', PACKAGE = 'sqlite3test', bikedb, stn_data, city)
}

#' rcpp_create_sqlite3_db
#'
#' Initial creation of SQLite3 database
#' 
#' @param bikedb A string containing the path to the Sqlite3 database to 
#'        be created.
#'
#' @return integer result code
#'
#' @noRd
rcpp_create_sqlite3_db <- function(bikedb) {
    .Call('sqlite3test_rcpp_create_sqlite3_db', PACKAGE = 'sqlite3test', bikedb)
}

#' compare_version_numbers
#'
#' Function to compare version numbers
#' First argument is compared to the second argument
#' Return value:
#' -1 = Argument one version lower than Argument two version
#' 0 = Argument one version equal to Argument two version
#' 1 = Argument one version higher than Argument two version
#'
#' @noRd
NULL

